### ISSUE TITLE
UCO price providers crash

### ISSUE THREAD

**Issue by bchamagne** [archethic-foundation/archethic-node#1017]
### Describe the problem you discovered

Issue in 1.0.8 found on testnet today: 

![paste](https://user-images.githubusercontent.com/74045243/237052282-268ac79b-16a4-4f7f-a0e4-2e977bb064fb.png)

This snowballs and make the node completely unavailable (due to max_restart_intensity)

**Comment by bchamagne** [comment]
Also found this:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of a float

    :erlang.binary_to_float("")
    (archethic 1.0.8-rc1) lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap.ex:49: anonymous fn/2 in Archethic.OracleChain.Services.UCOPrice.Providers.CoinMarketCap.fetch/1
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.60956695/1 in Archethic.OracleChain.Services.UCOPrice.Providers.CoinMarketCap.fetch/1>, ["usd"]]
```
