### ISSUE TITLE
ArgumentError  at GET /explorer/chain assign @uco_balance not available in eex template

### ISSUE THREAD

**Issue by imnik11** [archethic-foundation/archethic-node#122]
Description
Running iex -S mix 
Open browser http://localhost:4000/explorer/chain . or just click chain in navbar

Expected Behaviour

![expected](https://user-images.githubusercontent.com/45528152/138817710-8881eca1-90b1-4b0d-96ef-a0c42ddfe809.png)

Actual Behaviour
![CHAINS ROUTE](https://user-images.githubusercontent.com/45528152/138817299-77b33e53-4c42-4844-aa54-711327422d99.png)

**Comment by imnik11** [comment]
`2021-11-08 07:40:31.547 [error] #PID<0.11190.1> running ArchEthicWeb.Endpoint (connection #PID<0.2075.0>, stream id 32) terminated
Server: localhost:4000 (http)
Request: GET /explorer/chain
** (exit) an exception was raised:
    ** (ArgumentError) assign @uco_balance not available in eex template.

Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.

Available assigns: [:address, :chain_size, :conn, :last_checked?, :transaction_chain, :view_module, :view_template]

        (phoenix_html 2.14.3) lib/phoenix_html/engine.ex:139: Phoenix.HTML.Engine.fetch_assign!/2
        (archethic 0.12.4) lib/archethic_web/templates/explorer/chain.html.eex:84: ArchEthicWeb.ExplorerView."chain.html"/1
        (phoenix 1.5.7) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
        (phoenix 1.5.7) lib/phoenix/controller.ex:788: Phoenix.Controller.render_with_layouts/4
        (phoenix 1.5.7) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
        (archethic 0.12.4) lib/archethic_web/controllers/explorer_controller.ex:1: ArchEthicWeb.ExplorerController.action/2
        (archethic 0.12.4) lib/archethic_web/controllers/explorer_controller.ex:1: ArchEthicWeb.ExplorerController.phoenix_controller_pipeline/2
        (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (archethic 0.12.4) lib/archethic_web/endpoint.ex:1: ArchEthicWeb.Endpoint.plug_builder_call/2
        (archethic 0.12.4) lib/plug/debugger.ex:136: ArchEthicWeb.Endpoint."call (overridable 3)"/2
        (archethic 0.12.4) lib/archethic_web/endpoint.ex:1: ArchEthicWeb.Endpoint.call/2
        (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/nik/imnik11/archethic-node/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/nik/imnik11/archethic-node/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/nik/imnik11/archethic-node/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
`
