### ISSUE TITLE
Git push - error with mix dialyzer

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#524]
### Is your feature request related to a problem?

When we want to push an update, the mix dialyzer command doesn't work
@Neylix said to me to create "plts" folder in priv folder and that's ok
Could you update the documentation or add an automatic creation if the folder doesn't exist
Thx

```
× pre_push failed on `mix dialyzer`
** (exit) 1
    lib/mix/tasks/git_hooks/run.ex:185: Mix.Tasks.GitHooks.Run.error_exit/1
    lib/mix/tasks/git_hooks/run.ex:138: Mix.Tasks.GitHooks.Run.run_task/3
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    lib/mix/tasks/git_hooks/run.ex:63: Mix.Tasks.GitHooks.Run.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
error: impossible de pousser des références vers 'https://github.com/redDwarf03/archethic-node.git'
```

**Comment by samuel-uniris** [comment]
Closed by #531
