### ISSUE TITLE
Add Alpinejs functions in front end to avoid calls to backend

### ISSUE THREAD

**Issue by ambareesha7** [archethic-foundation/archethic-node#70]
Like, in transaction details

**Comment by ambareesha7** [comment]
Hi Sam I'm getting these errors to push the code into github 
there were lot of text on the terminal so I just copied last part of the error message
<pre>
1) doctest ArchEthic.P2P.MemTable.start_link/1 (18) (ArchEthic.P2P.MemTableTest)
     test/archethic/p2p/mem_table_test.exs:7
     match (=) failed
     code:  {:ok, _} = MemTable.start_link()
     left:  {:ok, _}
     right: {:error, {:already_started, #PID<0.8023.0>}}
     stacktrace:
       (for doctest at) lib/archethic/p2p/mem_table.ex:24: (test)

--max-failures reached, aborting test suite

Finished in 23.9 seconds (5.0s async, 18.8s sync)
148 doctests, 6 properties, 155 tests, 1 failure

Randomized with seed 403557
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
× pre_push failed on `mix test --trace`
** (exit) 1
    lib/mix/tasks/git_hooks/run.ex:185: Mix.Tasks.GitHooks.Run.error_exit/1
    lib/mix/tasks/git_hooks/run.ex:138: Mix.Tasks.GitHooks.Run.run_task/3
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    lib/mix/tasks/git_hooks/run.ex:63: Mix.Tasks.GitHooks.Run.run/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
error: failed to push some refs to 'https://github.com/ambareesha7/archethic-node.git'
➜  archethic-node git:(imple-alpine) 
</pre>
