### ISSUE TITLE
TransactionChain API : Error when pagingAddress param doesn't exist in the chain

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-node#782]
### Describe the problem you discovered

When we execute a graphql query to get a transactionChain with an address in parameter and a pagingAddress that doesn't exist in the chain itself, graphQL generates an error 

```
"# MatchError at POST /api/graphiql\n\nException:\n\n    ** (MatchError) no match of right hand side value: {:ok, \"CgCgHQBFCQigCKAwRVjIcUARQDihIRQDigCKAcUARQBFAOKAIoAigHFAEUA4oAqAaEqYtbf4p6FAGQAqIjy6/pvXzH4p+J5o5Xw2DR9XXn5fI78GBOPPIwfZ9t694q4+0EoZUQktmDrxtHXvtvXz3GOOPEovVndBampV7dXPE0sqsrR1xrwqWWwpQSIIJjISJGYztWKxY4YnLmaT9e9fmTbbMV/wAM4k/erADKeYToTzk6TjYAkfyK6sObBGCbb09H33oVp2Xs/Z5Fpaab19LCnF//AOaCtUAZzMRGY/gxnxssk7grr5Inlrc3FvhtoloLWUtNp/6lp/7JkT+Lfy/SuVSzZG63fXy+xOiLUpsmRrtLRBZMrW287r5cEEFKVKMHrt2qreWWk5a+iq/dpFrXQycVtGbu0Q2zftIUXTy+aQiAZxjtE+Znrvvw2SWObcoXprWvd/Yq6ZK0au2gyF3TL7TadKGxJSTnqAJO2+MyTUZJY5XUWm/b+wrNF2+lTS1t2ykIb/7FqJgdBEdd/KsccXdN77EszrunzcrQFgtwF8wElRBPlIxBGO3pOqxx5U+pWzpE29iwpN0pshIBS0IkmZkR5nb6VyrnyS+DvvzLaLci2q2vwhaUOthCiEFSQkKkiZ269R2+dk54ZXab0+31+5DSkjFcW5t1hJJPtGRg1+k8Bx8ONxucFXen1PIy4njdMqIr0DIAKgDigHFAEUJCKAKAIoAoB0AUARQBFAEUA4oAihIUA6AKAwRVjMcUARQDipARQBFQB0AUARQDigCKAcUAUAUA4oAihJqtbNTqC8ToQn+tSZT/AI7V4f4r+Jw4WPhrWTXR6r1rf29jpwYXP4nsdNDCXG3Ltq4K3EpBLQUkhUTBwJnaI2r89nlk5KM189f5PWSSVoxPXz/xwQgIccUQXXEhKiExEmANpj/dbRxR5Lei6LVEWzHxdfwFyi7caShbqI5idSSsiMFJ2x1kb9a6OGXiweNPRdP7Kt0x3vFFfCpft1ySUhZb1KUOoK8ZiBj/AFUYuH+Lll671XqkG/IyoCr1gqdvW9I1KVbKUcGDAGD0MeR+urrHKlH59sLVbk+W1f8A2ehYQ0q3WUtnUCobwFTv2jFQpSxcTpre/wDQ6Ga9uX1otrVuzQ0l2SFNgJSc9cxIjOx71rihFc03K6773RDssRwniN9ZgOWSysHDq4SAnw5g5PXOfLyh8ThxT+GWnl9SeVtHXZ4exdW6rVi9eCWhpIcUQUmACANiIztjv0rhnmlCXPKKtlqTObdm5tklu/4qlRbQrltpJCnEn+knocfXyrtxRjkaeLHvu3sq6lG11ZBq6XcMqNnbLaYSkIdUlIWUwN5AkHpNMmLw5f8ApK306C71NDfw7P8A5DaWbpoAEJb1pU355Ajz7GsWpy+F2n61qToWsOOLLay7yCtegI06TE9yADtvnr6HOaSTVX335A7LzSLpGt9qXGyIbaIClAxPl1npVuB/Es/AqUMVVLz6MjJhjkacuhz0qD6nkMMthtIgqSZM5jPXYbdZr1OF/Ec74nG+Iyur26a/712RjPFFQfKjMpCkxqESJr7mGSGS+V3Wj9zzWmtyNXIHFAEUARQDigCKAIoAigCKAKAdAFAFAFCQigHQBFAYYqxmOKkBFAEUA4oAigHFQAipARUAcUARQDigCKAIoSOKgFrFut4nSPCn8RxgVycVxmHhY3klV3XrXyZpjxym9EdG1eSlIetrYhBOgEg5ncGVDG+3lX5txmbLxM+bNK336fwexjgoRqKIoXdKvFoXZOKZSqCpbYEY6GAT+1YtQUE1JX37ltTzfFxf8MUWkv6GnV4WlchwGIUZPkDtvXrcK8Ob4mra+3psUdoYbvGblKrtp58pbCmQ4kOCTGI749aSlilGsbrXXWvuKZtuL1+ySkr4cGGloyothGr1SFYMyY8oiuaGKOR6Tt/X9US21ucewUbi6AW0gtpGnl6wCZJgASCTnpH+e7MuWFp6+ff72VR0HODIu0pe4WUBxoDmWqlEAjvqJ32wT09q5o8U4XHNs9n/AEv1LUnsZbTh92riAtG3OYP+1WkGBjAzpIkmNxW2XNjWPnarp3V+5CWp61hpyytg5evlp5Staw0ZSIzBMnECJ6+deJOUckqxq10vvz7RqlS1C3Va3KELTaNNgnwKSAFyDiI3GNzSanBtczf6fcaGDiKWL6zeaQhBLbUpa5KQqRB39sgRia6uHnPFkTb3fnp3r1so9UecTdvttchpxzkEkBOCPLbrg+9evLEpfHJamdisHefd8t50hsInUZI0wcemarmjywtLXv7kr1O6xxQlohC21lQ8AWIXJBEAqxAj+RXnS4dc2qfr5aexazcjiilOutrWtKW2lKWlSogCcAYjt7VyvAkk0t2TzFTMMXiXUtkW70KQSsLOcGNxGYyK6MuTnj8OklvWmtt/L5FUjWhi3uChpCQHT+LUSVzE+Q+ldPCfi3EcI97jfpr031ZTJghP3MTzCmVQoY6E191wXG4uMxc+N+68jzcmOWN0yuK7TMdAEUAUARQBFAEUA4oAihIRQgIoSOKAIoAigCgCKAxRVzMIoBxQBFAOKAIoAioA4oAigHFCRxQBFAEVAHFCS5hlKwVLVoAIEmInzzXlfiX4h+TiqjbfS6dea0ZvhxeIVcXvbu3ToSW2UaAoAN6SucRtuK+Ixvx5c025O+ruv6Z6bXKqRzy3x+9aZdt0urSUhUi4ScjY4O/WN62T4TG3Gf6P+PuTUmW2HFeLOXzVsVclKEhR1+DUDGFE9z7ZOKrn4bh4wc1rfz+leQt2dZCl27TidTpLQBU3b+NtsxEQTJGxiuBpSa9er0bJujkj7W3SEraedS4reEtABU7j8v5Nd3/62DacVS9yOZnLveO3F8svJaQ2EDIjUB2MHaJ+Z9K7cPB48a5W7KttnM5qpKguFziFR9K6+VbVoQer4fwu9RZFLbpbdfI5gAPMQmTkpMA7DHvXiZuIxudtWl9H89e9DRJmq5unbBIIcS6HSFJcXGhJHh0YwY3mOprHHiWbZVXlv535huiI481eIeYfUCFjAbTkk9j326HfarPg54mpRX172HNehC3U69cO8PQCm11FAQ5qKkCMHYH0mpmoxisrfxb6VX7hXsYm+H3i7e5S2HEeAjW4hWp2OgTnO/p5V1PPjjKLev7fMpTZxXVcolBUolGCFYIM7ER3r0b5qaK0WMqcUnZRCiA4rYRORHXzjuam4R0q30FHWQ2hhgu6kBKUCC2o6UmPDkz2ONvXNeb4jcqre9/uWLuGui5t3Q8lTgBhKm061JSMnfvE+0Vjni4yXL/BK2OkH3Wg2GAVMOQsOKaSQN8kY052zXI4J3zbrpb7ZaxMXGuQ+0hLrWlJAypyR4c9RH59hFTOFf8AL0f2F+Zq1ou20go0p0S2ohfTG8QdvLp6V1/h/GT4LLo9G1e38mWXGskdTFGdq/SE7PJCKkDioARUgIoAigCgCKAKEjigCKAIoAigCKAcVACKAxRVzMcVICKgDihIRQDigCKAIoBxQUOKEhFAEVALWrZ18/doJzE7Ae9cvE8Zg4aPNmkl+v03Lwxyn/yjWiyVaqDj7SnBMQlIIEjGqdh0r5nj/wD8ghkx8nCvV9Xa+nr+x2YuFcXczBxK9YtXtIQ+0/pJSGkaQOwIVk+g+tec+JzcXgUMj5qe739arp1+2hvHGoStGV83t7Zcm/vOSEDUw3HiWe5jt23rlh4eKd443e78jV6rUycN4kyi1DKnXAoLCW1SNIHWZiR13Ed63z4JOfNXfp+mxCZfxK/4fcNIdacbectlBaVuOLJWnqmDKRVMGHLBtSTXNpol/pLaNfCk3l46hT1sy2lwl1IS4lGsYB8IwZHSB1z3w4h48aajJutNnp83/PyCTZf/AMHzrPTfWNqSXSSbadW+5CZInsD09Ky/Ncs7xye3X+6282WrTU8ebG7W8Da2VwW3SeWSgkGCesQdt69/xsaX/pJWtzOmbEcAvn3gbnS2hvLiTlQROVgDBHv/AJrF8Zhgvg1/ny819AovqdG2v1cMfaRaLLoSQguPN5KQMjEwNq4Z4lmi3NV6J9fsSn\" <> ...}\n        (archethic 1.0.5) lib/archethic/db/embedded_impl/chain_reader.ex:251: Archethic.DB.EmbeddedImpl.ChainReader.read_transaction/5\n        (archethic 1.0.5) lib/archethic/db/embedded_impl/chain_reader.ex:321: Archethic.DB.EmbeddedImpl.ChainReader.do_scan_chain/4\n        (archethic 1.0.5) lib/archethic/db/embedded_impl/chain_reader.ex:236: Archethic.DB.EmbeddedImpl.ChainReader.do_process_get_chain/3\n        (archethic 1.0.5) lib/archethic/db/embedded_impl/chain_reader.ex:132: Archethic.DB.EmbeddedImpl.ChainReader.get_transaction_chain/4\n        (archethic 1.0.5) lib/archethic/transaction_chain.ex:1013: Archethic.TransactionChain.get_locally/2\n        (archethic 1.0.5) lib/archethic.ex:273: Archethic.get_transaction_chain_by_paging_address/2\n        (archethic 1.0.5) lib/archethic_web/graphql_schema/resolver.ex:142: ArchethicWeb.GraphQLSchema.Resolver.transaction_chain_by_paging_address/2\n        (absinthe 1.7.0) lib/absinthe/resolution.ex:206: Absinthe.Resolution.call/2\n        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1\n        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3\n
```

### Describe the solution you'd like

Manage the exception

**Comment by bchamagne** [comment]
@redDwarf03 do you have an example query where it fails? I was not able to reproduce.

I tried 

```
query {
  transactionChain(address: "EXISTING_ADDRESS", pagingAddress: "NON_EXISTING_ADDRESS" ) {
    address
    data { 
    	content 
    }
  }
}
```
```
query {
  transactionChain(address: "NON_EXISTING_ADDRESS", pagingAddress: "NON_EXISTING_ADDRESS" ) {
    address
    data { 
    	content 
    }
  }
}
```

and it returns without error

**Comment by samuelmanzanera** [comment]
Is it still relevant ?

**Comment by redDwarf03** [comment]
no, i test and it's ok now. Thx. I close the issue
